using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using KK.UI.UMG.Editor.Manifests;
using KK.UI.UMG.Editor.Pipeline;

namespace KK.UI.UMG.Editor.Generators
{
    public sealed class CSharpCodeGenerator
    {
        public const string Header = "// Generated by KK_UI_UMG v0.9. Do not modify.";

        public IReadOnlyList<string> Generate(KKUIPipelineContext context)
        {
            var scriptsRoot = Path.Combine(context.GeneratedRoot, "Scripts");
            Directory.CreateDirectory(scriptsRoot);

            var files = new List<string>
            {
                WriteGenerated(Path.Combine(scriptsRoot, $"{context.Codegen.View.ClassName}.Generated.cs"), GenerateView(context)),
                WriteGenerated(Path.Combine(scriptsRoot, $"{context.Codegen.Controller.ClassName}.Generated.cs"), GenerateController(context)),
                WriteGenerated(Path.Combine(scriptsRoot, $"{context.Codegen.ViewModel.ClassName}.Generated.cs"), GenerateViewModel(context)),
                WriteGenerated(Path.Combine(scriptsRoot, $"{context.Codegen.Controller.ClassName}Registration.Generated.cs"), GenerateControllerRegistration(context)),
                WriteGenerated(Path.Combine(scriptsRoot, $"{context.Package.PackageId}Bus.Generated.cs"), GenerateBus(context)),
                WriteGenerated(Path.Combine(scriptsRoot, $"{context.Package.PackageId}Strings.Generated.cs"), GenerateStrings(context))
            };

            return files;
        }

        private static string GenerateView(KKUIPipelineContext context)
        {
            var controls = GetBindableControls(context.Layout.Root).ToList();
            var builder = new StringBuilder();
            builder.AppendLine(Header);
            builder.AppendLine("using TMPro;");
            builder.AppendLine("using UnityEngine;");
            builder.AppendLine("using UnityEngine.UI;");
            builder.AppendLine("using KK.UI.UMG;");
            if (controls.Any(node => node.Type == "VerticalList"))
            {
                builder.AppendLine("using KK.UI.UMG.Components;");
            }
            builder.AppendLine();
            builder.AppendLine($"namespace {context.Codegen.Namespace}");
            builder.AppendLine("{");
            builder.AppendLine($"    public partial class {context.Codegen.View.ClassName} : {context.Codegen.View.BaseClass}");
            builder.AppendLine("    {");
            foreach (var node in controls)
            {
                builder.AppendLine($"        [SerializeField] private {GetControlType(node)} {GetFieldName(node.Id)};");
            }

            builder.AppendLine();
            foreach (var node in controls)
            {
                builder.AppendLine($"        public {GetControlType(node)} {ToPascal(node.Id)} => {GetFieldName(node.Id)};");
            }

            builder.AppendLine();
            builder.AppendLine($"        public {context.Codegen.Controller.ClassName} TypedController => ({context.Codegen.Controller.ClassName})Controller;");
            builder.AppendLine();
            builder.AppendLine("        protected override void BindEvents()");
            builder.AppendLine("        {");
            foreach (var evt in GetGeneratedEvents(context))
            {
                builder.AppendLine($"            {BuildAddListener(evt)}");
            }

            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        protected override void UnbindEvents()");
            builder.AppendLine("        {");
            foreach (var evt in GetGeneratedEvents(context))
            {
                builder.AppendLine($"            {BuildRemoveListener(evt)}");
            }

            builder.AppendLine("        }");
            foreach (var evt in GetGeneratedEvents(context))
            {
                builder.AppendLine();
                builder.AppendLine($"        private void Handle{evt.Handler}({evt.ParameterDeclaration})");
                builder.AppendLine("        {");
                builder.AppendLine($"            TypedController.{evt.Handler}({evt.ParameterNames});");
                builder.AppendLine("        }");
            }

            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static string GenerateController(KKUIPipelineContext context)
        {
            var builder = new StringBuilder();
            builder.AppendLine(Header);
            builder.AppendLine("using System.Collections.Generic;");
            builder.AppendLine("using KK.UI.UMG;");
            builder.AppendLine("using KK.UI.UMG.Binding;");
            if (context.Bindings.Events.Any(evt => !string.IsNullOrWhiteSpace(evt.Channel)))
            {
                builder.AppendLine("using KK.UI.UMG.MessageBus;");
            }
            builder.AppendLine();
            builder.AppendLine($"namespace {context.Codegen.Namespace}");
            builder.AppendLine("{");
            builder.AppendLine($"    public partial class {context.Codegen.Controller.ClassName} : {context.Codegen.Controller.BaseClass}");
            builder.AppendLine("    {");
            foreach (var service in GetRequiredServices(context))
            {
                builder.AppendLine($"        protected {ToGlobalTypeName(service.Type)} {service.Property} {{ get; private set; }}");
            }

            if ((context.Codegen.RequiredServices?.Count ?? 0) > 0)
            {
                builder.AppendLine();
            }

            builder.AppendLine("        protected override void OnViewBound(UIViewBase view)");
            builder.AppendLine("        {");
            builder.AppendLine("            Binder.Configure(view, new List<ViewModelBinding>");
            builder.AppendLine("            {");
            foreach (var binding in context.Bindings.Bindings)
            {
                builder.AppendLine("                new ViewModelBinding");
                builder.AppendLine("                {");
                builder.AppendLine($"                    ControlId = \"{binding.ControlId}\",");
                builder.AppendLine($"                    FieldId = \"{binding.FieldId}\",");
                builder.AppendLine("                    Mode = BindingMode.OneWay,");
                builder.AppendLine($"                    Property = \"{binding.Property}\"");
                builder.AppendLine("                },");
            }
            builder.AppendLine("            });");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        public override void Initialize(MessagePayload payload)");
            builder.AppendLine("        {");
            foreach (var service in GetRequiredServices(context))
            {
                builder.AppendLine($"            {service.Property} = RequireService<{ToGlobalTypeName(service.Type)}>();");
            }

            builder.AppendLine("            OnGeneratedInitialize(payload);");
            builder.AppendLine("            OnInitializeCore(payload);");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        partial void OnInitializeCore(MessagePayload payload);");
            builder.AppendLine();
            foreach (var evt in GetGeneratedEvents(context))
            {
                builder.AppendLine($"        public void {evt.Handler}({evt.ParameterDeclaration})");
                builder.AppendLine("        {");
                if (!evt.HasParameters)
                {
                    foreach (var update in evt.SourceEvent?.Updates ?? new List<UiEventUpdateSpec>())
                    {
                        builder.AppendLine($"            Store.Update({context.Codegen.ViewModel.ClassName}.Fields.{ToPascal(update.FieldId)}, {ToCSharpLiteral(update.Value)});");
                    }
                    if (evt.SourceEvent?.Updates != null && evt.SourceEvent.Updates.Count > 0)
                    {
                        builder.AppendLine("            Flush();");
                    }
                    if (!string.IsNullOrWhiteSpace(evt.SourceEvent?.Channel))
                    {
                        builder.AppendLine();
                        builder.AppendLine("            var payload = new MessagePayload();");
                        foreach (var fieldId in evt.SourceEvent.ChannelPayloadFields ?? new List<string>())
                        {
                            builder.AppendLine($"            payload.Set({context.Codegen.ViewModel.ClassName}.Fields.{ToPascal(fieldId)}, Store.Get<{GetFieldType(context, fieldId)}>({context.Codegen.ViewModel.ClassName}.Fields.{ToPascal(fieldId)}));");
                        }
                        builder.AppendLine($"            UIMessageBus.Publish({context.Package.PackageId}Bus.{GetBusConstantName(context, evt.SourceEvent.Channel)}, payload);");
                    }
                }
                builder.AppendLine($"            OnGeneratedEvent(\"{evt.Handler}\", {BuildGeneratedEventArgs(evt)});");
                builder.AppendLine($"            {evt.Handler}Core({evt.ParameterNames});");
                builder.AppendLine("        }");
                builder.AppendLine();
                builder.AppendLine($"        partial void {evt.Handler}Core({evt.ParameterDeclaration});");
                builder.AppendLine();
            }
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static string GenerateViewModel(KKUIPipelineContext context)
        {
            var builder = new StringBuilder();
            builder.AppendLine(Header);
            builder.AppendLine();
            builder.AppendLine($"namespace {context.Codegen.Namespace}");
            builder.AppendLine("{");
            builder.AppendLine($"    public static class {context.Codegen.ViewModel.ClassName}");
            builder.AppendLine("    {");
            builder.AppendLine("        public static class Fields");
            builder.AppendLine("        {");
            foreach (var field in context.Bindings.Mvvm.Fields)
            {
                builder.AppendLine($"            public const string {ToPascal(field.Id)} = \"{field.Id}\";");
            }
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static string GenerateControllerRegistration(KKUIPipelineContext context)
        {
            return $@"{Header}
using UnityEngine;
using KK.UI.UMG;
using KK.UI.UMG.Internal;
using KK.UI.UMG.Localization;
using KK.UI.UMG.MessageBus;

namespace {context.Codegen.Namespace}
{{
    public static class {context.Codegen.Controller.ClassName}Registration
    {{
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
        private static void Register()
        {{
            ControllerFactoryRegistry.Register(""{context.Package.PackageId}"", () => new {context.Codegen.Controller.ClassName}());
{GenerateRouteRegistrations(context)}
            UILocalizationService.Instance.RegisterTable(""{context.Package.PackageId}"", {context.Package.PackageId}Strings.CreateTable());
        }}
    }}
}}
";
        }

        private static string GenerateBus(KKUIPipelineContext context)
        {
            var builder = new StringBuilder();
            builder.AppendLine(Header);
            builder.AppendLine();
            builder.AppendLine($"namespace {context.Codegen.Namespace}");
            builder.AppendLine("{");
            builder.AppendLine($"    public static class {context.Package.PackageId}Bus");
            builder.AppendLine("    {");
            foreach (var channel in GetAllRelativeChannels(context))
            {
                builder.AppendLine($"        public const string {GetBusConstantName(context, channel)} = \"{BusChannelUtility.BuildFullChannel(context.Package.PackageId, channel)}\";");
            }
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static string GenerateStrings(KKUIPipelineContext context)
        {
            var builder = new StringBuilder();
            builder.AppendLine(Header);
            builder.AppendLine("using System.Collections.Generic;");
            builder.AppendLine("using KK.UI.UMG.Localization;");
            builder.AppendLine();
            builder.AppendLine($"namespace {context.Codegen.Namespace}");
            builder.AppendLine("{");
            builder.AppendLine($"    public static class {context.Package.PackageId}Strings");
            builder.AppendLine("    {");
            foreach (var key in context.Strings.Strings.Keys.OrderBy(key => key, StringComparer.Ordinal))
            {
                builder.AppendLine($"        public const string {ToStringKeyConstantName(key)} = \"{EscapeString(key)}\";");
            }
            builder.AppendLine();
            builder.AppendLine("        public static UILocalizedStringTable CreateTable()");
            builder.AppendLine("        {");
            builder.AppendLine("            return new UILocalizedStringTable(");
            builder.AppendLine($"                \"{context.Package.PackageId}\",");
            builder.AppendLine($"                \"{EscapeString(context.Strings.DefaultCulture)}\",");
            builder.AppendLine("                new Dictionary<string, Dictionary<string, string>>");
            builder.AppendLine("                {");
            foreach (var entry in context.Strings.Strings.OrderBy(entry => entry.Key, StringComparer.Ordinal))
            {
                builder.AppendLine($"                    [{ToStringKeyConstantName(entry.Key)}] = new Dictionary<string, string>");
                builder.AppendLine("                    {");
                foreach (var localizedValue in entry.Value.OrderBy(value => value.Key, StringComparer.Ordinal))
                {
                    builder.AppendLine($"                        [\"{EscapeString(localizedValue.Key)}\"] = \"{EscapeString(localizedValue.Value)}\",");
                }
                builder.AppendLine("                    },");
            }
            builder.AppendLine("                });");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static string WriteGenerated(string path, string contents)
        {
            if (!path.EndsWith(".Generated.cs", StringComparison.Ordinal))
            {
                throw new InvalidOperationException($"Refusing to write non-generated file '{path}'.");
            }

            var firstLine = File.Exists(path) ? File.ReadLines(path).FirstOrDefault() : null;
            if (File.Exists(path) && (firstLine == null || (!firstLine.Contains("Generated by KKUIPipeline") && !firstLine.Contains("Generated by KK_UI_UMG"))))
            {
                throw new InvalidOperationException($"Refusing to overwrite '{path}' because it has no generated header.");
            }

            File.WriteAllText(path, contents, Encoding.UTF8);
            return path;
        }

        private static IEnumerable<UiLayoutNode> GetBindableControls(UiLayoutNode root)
        {
            var nodes = new List<UiLayoutNode>();
            ValidatorUtilityProxy.Walk(root, node =>
            {
                if (IsBindableControl(node.Type))
                {
                    nodes.Add(node);
                }
            });
            return nodes;
        }

        private static string GetControlType(UiLayoutNode node)
        {
            return node.Type switch
            {
                "Text" => "TextMeshProUGUI",
                "Image" => "Image",
                "Button" => "Button",
                "RawImage" => "RawImage",
                "Toggle" => "Toggle",
                "Slider" => "Slider",
                "InputField" => "TMP_InputField",
                "Dropdown" => "TMP_Dropdown",
                "Scrollbar" => "Scrollbar",
                "ScrollView" => "ScrollRect",
                "VerticalList" => "UIListView",
                _ => throw new NotSupportedException(node.Type)
            };
        }

        private static IEnumerable<GeneratedEventSpec> GetGeneratedEvents(KKUIPipelineContext context)
        {
            var nodesById = new Dictionary<string, UiLayoutNode>();
            ValidatorUtilityProxy.Walk(context.Layout.Root, node =>
            {
                if (!string.IsNullOrWhiteSpace(node.Id))
                {
                    nodesById[node.Id] = node;
                }
            });

            foreach (var evt in context.Bindings.Events)
            {
                if (!nodesById.TryGetValue(evt.ControlId, out var node))
                {
                    continue;
                }

                yield return CreateEventSpec(node, evt);
            }

            foreach (var node in nodesById.Values)
            {
                if (node.Type != "VerticalList")
                {
                    continue;
                }

                foreach (var itemEvent in node.VerticalList?.ItemEvents ?? new List<UiListItemEventSpec>())
                {
                    yield return new GeneratedEventSpec
                    {
                        ControlId = node.Id,
                        Handler = itemEvent.Handler,
                        EventName = itemEvent.Event,
                        ParameterDeclaration = "int index, string itemId",
                        ParameterNames = "index, itemId",
                        HasParameters = true
                    };
                }
            }
        }

        private static GeneratedEventSpec CreateEventSpec(UiLayoutNode node, UiEventSpec evt)
        {
            var spec = new GeneratedEventSpec
            {
                ControlId = evt.ControlId,
                Handler = evt.Handler,
                EventName = evt.Event,
                SourceEvent = evt
            };

            switch (node.Type)
            {
                case "Toggle":
                    spec.ParameterDeclaration = "bool value";
                    spec.ParameterNames = "value";
                    spec.HasParameters = true;
                    break;
                case "Slider":
                case "Scrollbar":
                    spec.ParameterDeclaration = "float value";
                    spec.ParameterNames = "value";
                    spec.HasParameters = true;
                    break;
                case "InputField":
                    spec.ParameterDeclaration = "string value";
                    spec.ParameterNames = "value";
                    spec.HasParameters = true;
                    break;
                case "Dropdown":
                    spec.ParameterDeclaration = "int value";
                    spec.ParameterNames = "value";
                    spec.HasParameters = true;
                    break;
                case "VerticalList":
                    spec.ParameterDeclaration = "int index, string itemId";
                    spec.ParameterNames = "index, itemId";
                    spec.HasParameters = true;
                    break;
                default:
                    spec.ParameterDeclaration = string.Empty;
                    spec.ParameterNames = string.Empty;
                    spec.HasParameters = false;
                    break;
            }

            return spec;
        }

        private static string BuildAddListener(GeneratedEventSpec evt)
        {
            var field = GetFieldName(evt.ControlId);
            return evt.EventName switch
            {
                "onClick" => $"{field}.onClick.AddListener(Handle{evt.Handler});",
                "onValueChanged" => $"{field}.onValueChanged.AddListener(Handle{evt.Handler});",
                "onEndEdit" => $"{field}.onEndEdit.AddListener(Handle{evt.Handler});",
                "onItemClick" => $"{field}.ItemClicked += Handle{evt.Handler};",
                _ => $"// Unsupported event '{evt.EventName}'"
            };
        }

        private static string BuildRemoveListener(GeneratedEventSpec evt)
        {
            var field = GetFieldName(evt.ControlId);
            return evt.EventName switch
            {
                "onClick" => $"{field}.onClick.RemoveListener(Handle{evt.Handler});",
                "onValueChanged" => $"{field}.onValueChanged.RemoveListener(Handle{evt.Handler});",
                "onEndEdit" => $"{field}.onEndEdit.RemoveListener(Handle{evt.Handler});",
                "onItemClick" => $"{field}.ItemClicked -= Handle{evt.Handler};",
                _ => $"// Unsupported event '{evt.EventName}'"
            };
        }

        private static string BuildGeneratedEventArgs(GeneratedEventSpec evt)
        {
            return evt.HasParameters ? $"new object[] {{ {evt.ParameterNames} }}" : "new object[0]";
        }

        private static string GetFieldName(string id)
        {
            return "_" + char.ToLowerInvariant(ToPascal(id)[0]) + ToPascal(id).Substring(1);
        }

        private static string ToPascal(string value)
        {
            return string.Concat(value.Split('_', '-', ' ').Where(part => part.Length > 0).Select(part => char.ToUpperInvariant(part[0]) + part.Substring(1)));
        }

        private static string ToStringKeyConstantName(string value)
        {
            return string.Concat(value.Split('_', '-', '.', ' ').Where(part => part.Length > 0).Select(part => char.ToUpperInvariant(part[0]) + part.Substring(1)));
        }

        private static string GetBusConstantName(KKUIPipelineContext context, string relativeChannel)
        {
            return BusChannelUtility.ToConstantName(context.Package.PackageId, relativeChannel);
        }

        private static IEnumerable<string> GetAllRelativeChannels(KKUIPipelineContext context)
        {
            foreach (var route in context.Codegen.Bus?.Routes ?? new List<UiBusRouteSpec>())
            {
                if (!string.IsNullOrWhiteSpace(route.Channel))
                {
                    yield return route.Channel;
                }
            }

            foreach (var evt in context.Bindings.Events)
            {
                if (!string.IsNullOrWhiteSpace(evt.Channel))
                {
                    yield return evt.Channel;
                }
            }
        }

        private static string GenerateRouteRegistrations(KKUIPipelineContext context)
        {
            var builder = new StringBuilder();
            foreach (var route in context.Codegen.Bus?.Routes ?? new List<UiBusRouteSpec>())
            {
                var action = route.Action == "Close" ? "Close" : "Open";
                builder.AppendLine($"            UIBusRouteRegistry.Register(\"{context.Package.PackageId}\", {context.Package.PackageId}Bus.{GetBusConstantName(context, route.Channel)}, UIBusRouteAction.{action});");
            }

            return builder.ToString().TrimEnd();
        }

        private static string GetFieldType(KKUIPipelineContext context, string fieldId)
        {
            var field = context.Bindings.Mvvm.Fields.FirstOrDefault(item => item.Id == fieldId);
            return field?.Type switch
            {
                "string" => "string",
                "int" => "int",
                "float" => "float",
                "bool" => "bool",
                "Sprite" => "UnityEngine.Sprite",
                "Texture" => "UnityEngine.Texture",
                "IReadOnlyList<MessagePayload>" => "IReadOnlyList<MessagePayload>",
                _ => "object"
            };
        }

        private static string ToCSharpLiteral(object value)
        {
            if (value == null)
            {
                return "null";
            }

            if (value is bool boolean)
            {
                return boolean ? "true" : "false";
            }

            if (value is string text)
            {
                return "\"" + EscapeString(text) + "\"";
            }

            return value.ToString();
        }

        private static string ToGlobalTypeName(string typeName)
        {
            var trimmed = typeName?.Trim() ?? string.Empty;
            return trimmed.StartsWith("global::", StringComparison.Ordinal) ? trimmed : $"global::{trimmed}";
        }

        private static IEnumerable<UiRequiredServiceSpec> GetRequiredServices(KKUIPipelineContext context)
        {
            return (context.Codegen.RequiredServices ?? new List<UiRequiredServiceSpec>())
                .Where(service => service != null && !string.IsNullOrWhiteSpace(service.Type) && !string.IsNullOrWhiteSpace(service.Property));
        }

        private static string EscapeString(string text)
        {
            return (text ?? string.Empty)
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\r", "\\r")
                .Replace("\n", "\\n");
        }

        private static bool IsBindableControl(string type)
        {
            return type == "Text" ||
                type == "Image" ||
                type == "Button" ||
                type == "RawImage" ||
                type == "Toggle" ||
                type == "Slider" ||
                type == "InputField" ||
                type == "Dropdown" ||
                type == "Scrollbar" ||
                type == "ScrollView" ||
                type == "VerticalList";
        }

        private sealed class GeneratedEventSpec
        {
            public string ControlId { get; set; }
            public string Handler { get; set; }
            public string EventName { get; set; }
            public string ParameterDeclaration { get; set; } = string.Empty;
            public string ParameterNames { get; set; } = string.Empty;
            public bool HasParameters { get; set; }
            public UiEventSpec SourceEvent { get; set; }
        }

        private static class ValidatorUtilityProxy
        {
            public static void Walk(UiLayoutNode node, Action<UiLayoutNode> visitor)
            {
                if (node == null)
                {
                    return;
                }

                visitor(node);
                foreach (var child in node.Children ?? new List<UiLayoutNode>())
                {
                    Walk(child, visitor);
                }
            }
        }
    }
}
