using System.Collections.Generic;
using System.Reflection;
using NUnit.Framework;
using KK.UI.UMG.Editor.Generators;
using KK.UI.UMG.Editor.Manifests;
using KK.UI.UMG.Editor.Pipeline;

namespace KK.UI.UMG.Editor.Tests
{
    public sealed class CSharpCodeGeneratorV03Tests
    {
        [Test]
        public void GeneratedHeaderUsesKkUiUmgBrand()
        {
            Assert.That(CSharpCodeGenerator.Header, Is.EqualTo("// Generated by KK_UI_UMG v0.9. Do not modify."));
        }

        [Test]
        public void GeneratedViewUsesTypedControllerForEvents()
        {
            var source = InvokeGenerator("GenerateView", CreateContext());

            Assert.That(source, Does.Contain("public TestController TypedController => (TestController)Controller;"));
            Assert.That(source, Does.Contain("TypedController.OnConfirmRequested();"));
            Assert.That(source, Does.Not.Contain("((TestController)Controller).OnConfirmRequested();"));
        }

        [Test]
        public void GeneratedControllerDoesNotEmitLifecycleOverrides()
        {
            var source = InvokeGenerator("GenerateController", CreateContext());

            Assert.That(source, Does.Not.Contain("override void OnPreOpen"));
            Assert.That(source, Does.Not.Contain("override void OnOpened"));
            Assert.That(source, Does.Not.Contain("override void OnActivated"));
            Assert.That(source, Does.Not.Contain("override void OnDeactivated"));
            Assert.That(source, Does.Not.Contain("override void OnPreClose"));
            Assert.That(source, Does.Not.Contain("override void OnClosed"));
        }

        [Test]
        public void GeneratedRegistrationUsesStaticFactoryRegistry()
        {
            var source = InvokeGenerator("GenerateControllerRegistration", CreateContext());

            Assert.That(source, Does.Contain("ControllerFactoryRegistry.Register(\"TestBox\", () => new TestController());"));
            Assert.That(source, Does.Not.Contain("UIManager.RegisterControllerFactory"));
            Assert.That(source, Does.Not.Contain("UIMessageBus.Subscribe"));
        }

        [Test]
        public void GeneratedRegistrationRegistersBusRouteMetadata()
        {
            var source = InvokeGenerator("GenerateControllerRegistration", CreateContextWithBus());

            Assert.That(source, Does.Contain("UIBusRouteRegistry.Register(\"TestBox\", TestBoxBus.TestBoxInOpenRequested, UIBusRouteAction.Open);"));
            Assert.That(source, Does.Not.Contain("UIMessageBus.Subscribe"));
        }

        [Test]
        public void GeneratedBusContainsChannelConstants()
        {
            var source = InvokeGenerator("GenerateBus", CreateContextWithBus());

            Assert.That(source, Does.Contain("public static class TestBoxBus"));
            Assert.That(source, Does.Contain("public const string TestBoxInOpenRequested = \"ui.TestBox.in.open_requested\";"));
            Assert.That(source, Does.Contain("public const string TestBoxOutConfirmResult = \"ui.TestBox.out.confirm_result\";"));
        }

        [Test]
        public void GeneratedControllerPublishesOutboundChannel()
        {
            var source = InvokeGenerator("GenerateController", CreateContextWithBus());

            Assert.That(source, Does.Contain("using KK.UI.UMG.MessageBus;"));
            Assert.That(source, Does.Contain("payload.Set(TestViewModel.Fields.Message, Store.Get<string>(TestViewModel.Fields.Message));"));
            Assert.That(source, Does.Contain("UIMessageBus.Publish(TestBoxBus.TestBoxOutConfirmResult, payload);"));
        }

        [Test]
        public void GeneratedStringsContainsRuntimeTable()
        {
            var source = InvokeGenerator("GenerateStrings", CreateContextWithLocalization());

            Assert.That(source, Does.Contain("public static class TestBoxStrings"));
            Assert.That(source, Does.Contain("public const string MessageDefault = \"message.default\";"));
            Assert.That(source, Does.Contain("new UILocalizedStringTable("));
            Assert.That(source, Does.Contain("\"zh-Hans\""));
        }

        [Test]
        public void GeneratedControllerDoesNotInitializeStaticLocalizedFields()
        {
            var source = InvokeGenerator("GenerateController", CreateContextWithLocalization());

            Assert.That(source, Does.Not.Contain("using KK.UI.UMG.Localization;"));
            Assert.That(source, Does.Contain("public override void Initialize(MessagePayload payload)"));
            Assert.That(source, Does.Not.Contain("UILocalizationService.Instance.Resolve"));
            Assert.That(source, Does.Not.Contain("Store.Update(TestViewModel.Fields.Message"));
            Assert.That(source, Does.Contain("OnGeneratedInitialize(payload);"));
            Assert.That(source, Does.Contain("partial void OnInitializeCore(MessagePayload payload);"));
            Assert.That(source, Does.Not.Contain("            Flush();"));
        }

        [Test]
        public void GeneratedControllerRequiresServicesBeforePartialInitialize()
        {
            var source = InvokeGenerator("GenerateController", CreateContextWithRequiredService());

            Assert.That(source, Does.Contain("protected global::Game.Inventory.IInventoryService InventoryService { get; private set; }"));
            Assert.That(source, Does.Contain("InventoryService = RequireService<global::Game.Inventory.IInventoryService>();"));
            Assert.That(
                source.IndexOf("InventoryService = RequireService", System.StringComparison.Ordinal),
                Is.LessThan(source.IndexOf("OnGeneratedInitialize(payload);", System.StringComparison.Ordinal)));
        }

        [Test]
        public void GeneratedViewDoesNotAccessRequiredServices()
        {
            var source = InvokeGenerator("GenerateView", CreateContextWithRequiredService());

            Assert.That(source, Does.Not.Contain("IInventoryService"));
            Assert.That(source, Does.Not.Contain("RequireService"));
        }

        [Test]
        public void GeneratedRegistrationRegistersLocalizationTable()
        {
            var source = InvokeGenerator("GenerateControllerRegistration", CreateContextWithLocalization());

            Assert.That(source, Does.Contain("UILocalizationService.Instance.RegisterTable(\"TestBox\", TestBoxStrings.CreateTable());"));
        }

        [Test]
        public void GeneratedV052EventUsesTypedParameters()
        {
            var context = CreateContext();
            context.Layout.Root.Children.Add(new UiLayoutNode { Type = "Slider", Id = "VolumeSlider" });
            context.Bindings.Events.Add(new UiEventSpec
            {
                ControlId = "VolumeSlider",
                Event = "onValueChanged",
                Handler = "OnVolumeChanged"
            });

            var viewSource = InvokeGenerator("GenerateView", context);
            var controllerSource = InvokeGenerator("GenerateController", context);

            Assert.That(viewSource, Does.Contain("_volumeSlider.onValueChanged.AddListener(HandleOnVolumeChanged);"));
            Assert.That(viewSource, Does.Contain("private void HandleOnVolumeChanged(float value)"));
            Assert.That(viewSource, Does.Contain("TypedController.OnVolumeChanged(value);"));
            Assert.That(controllerSource, Does.Contain("public void OnVolumeChanged(float value)"));
            Assert.That(controllerSource, Does.Contain("OnGeneratedEvent(\"OnVolumeChanged\", new object[] { value });"));
            Assert.That(controllerSource, Does.Contain("partial void OnVolumeChangedCore(float value);"));
            Assert.That(controllerSource, Does.Not.Contain("Store.Update(TestViewModel.Fields.Volume"));
        }

        private static string InvokeGenerator(string methodName, KKUIPipelineContext context)
        {
            var method = typeof(CSharpCodeGenerator).GetMethod(methodName, BindingFlags.NonPublic | BindingFlags.Static);
            Assert.That(method, Is.Not.Null);
            return (string)method.Invoke(null, new object[] { context });
        }

        private static KKUIPipelineContext CreateContext()
        {
            return new KKUIPipelineContext
            {
                Package = new UiPackageManifest
                {
                    PackageId = "TestBox",
                    Namespace = "Game.UI.Tests"
                },
                Codegen = new UiCodegenManifest
                {
                    Namespace = "Game.UI.Tests",
                    View = new UiViewCodegen { ClassName = "TestView", BaseClass = "UIViewBase" },
                    Controller = new UiControllerCodegen { ClassName = "TestController", BaseClass = "UIControllerBase" },
                    ViewModel = new UiViewModelCodegen { ClassName = "TestViewModel" }
                },
                Layout = new UiLayoutManifest
                {
                    Root = new UiLayoutNode
                    {
                        Type = "Panel",
                        Id = "Root",
                        Children = new List<UiLayoutNode>
                        {
                            new UiLayoutNode { Type = "Text", Id = "MessageText", Text = new UiTextSpec { Value = "message" } },
                            new UiLayoutNode { Type = "Button", Id = "ConfirmButton" }
                        }
                    }
                },
                Bindings = new UiBindingsManifest
                {
                    Mvvm = new UiMvvmSection
                    {
                        Fields = new List<UiViewModelFieldSpec>
                        {
                            new UiViewModelFieldSpec { Id = "Message", Type = "string" }
                        }
                    },
                    Bindings = new List<UiBindingSpec>
                    {
                        new UiBindingSpec
                        {
                            ControlId = "MessageText",
                            FieldId = "Message",
                            Mode = "OneWay",
                            Property = "text"
                        }
                    },
                    Events = new List<UiEventSpec>
                    {
                        new UiEventSpec
                        {
                            ControlId = "ConfirmButton",
                            Event = "onClick",
                            Handler = "OnConfirmRequested"
                        }
                    }
                }
            };
        }

        private static KKUIPipelineContext CreateContextWithLocalization()
        {
            var context = CreateContext();
            context.Layout.Root.Children[0].Text = new UiTextSpec { LocKey = "message.default" };
            context.Bindings.Mvvm.Fields.Clear();
            context.Bindings.Bindings.Clear();
            context.Strings = new UiStringsManifest
            {
                SchemaVersion = "1.0",
                DefaultCulture = "zh-Hans",
                Cultures = new List<string> { "zh-Hans", "en-US" },
                Strings = new Dictionary<string, Dictionary<string, string>>
                {
                    ["message.default"] = new Dictionary<string, string>
                    {
                        ["zh-Hans"] = "默认",
                        ["en-US"] = "Default"
                    }
                }
            };
            return context;
        }

        private static KKUIPipelineContext CreateContextWithBus()
        {
            var context = CreateContext();
            context.Codegen.Bus = new UiBusCodegen
            {
                Routes = new List<UiBusRouteSpec>
                {
                    new UiBusRouteSpec { Channel = "in.open_requested", Action = "Open" }
                }
            };
            context.Bindings.Events[0].Channel = "out.confirm_result";
            context.Bindings.Events[0].ChannelPayloadFields = new List<string> { "Message" };
            return context;
        }

        private static KKUIPipelineContext CreateContextWithRequiredService()
        {
            var context = CreateContext();
            context.Codegen.RequiredServices = new List<UiRequiredServiceSpec>
            {
                new UiRequiredServiceSpec
                {
                    Type = "Game.Inventory.IInventoryService",
                    Property = "InventoryService"
                }
            };
            return context;
        }
    }
}
